name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' # force php8.3
        tools: composer

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Upload vendor as artifact
      uses: actions/upload-artifact@v4
      with:
        name: vendor
        path: vendor

    - name: Run PHPCS
      run: ./vendor/bin/phpcs --standard=PSR12 ./app

  test:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer

    - name: Download vendor artifact
      uses: actions/download-artifact@v4
      with:
        name: vendor
        path: vendor

    - name: Run PHPCS
      run: ./vendor/bin/phpcs --standard=PSR12 .
