name: Run PHP Code Sniffer

on:
  workflow_run:
    workflows: ["PHP Composer"]
    types:
      - completed

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Download vendor artifact
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor

      - name: Run PHPCS
        run: ./vendor/bin/phpcs --standard=PSR12 .
